#ATMega328p
all-328:
	make -f Makefile.328 all
	
clean-328:
	make -f Makefile.328 clean

fuse-328:
	make -f Makefile.328 fuse

flash-328:
	make -f Makefile.328 flash

lock-328:
	make -f Makefile.328 lock
	
#ATMega168p
all-168:
	make -f Makefile.168 all
	
clean-168:
	make -f Makefile.168 clean

fuse-168:
	make -f Makefile.168 fuse

flash-168:
	make -f Makefile.168 flash

lock-168:
	make -f Makefile.168 lock


		